steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'archive-html'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Archiving HTML files from GCE VM..."
        gcloud compute ssh --zone=${_ZONE} ubuntu@${_GCE_VM} --command "tar -czf /tmp/latest_html.tar.gz -C /var/www/html ."

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'download-html'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Downloading HTML archive from the GCE VM..."
        gcloud compute scp ubuntu@${_GCE_VM}:/tmp/latest_html.tar.gz /workspace/latest_html.tar.gz --zone=${_ZONE}

  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'upload-html'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Uploading HTML archive to GCS bucket..."
        gsutil cp /workspace/latest_html.tar.gz gs://${_BUCKET}/latest_html.tar.gz

  - name: 'google/cloud-sdk:slim'
    id: 'authenticate-gke'
    entrypoint: 'sh'
    args:
      - -c
      - |
        gcloud container clusters get-credentials ${_CLUSTER} --region ${_ZONE}
        
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'copy-to-pod'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        kubectl get pods -n free
        kubectl cp /workspace/latest_html.tar.gz ${_NAMESPACE}/${_POD_NAME}:/tmp/ -n ${_NAMESPACE}

  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'extract-html'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Extracting HTML files inside the GKE pod..."
        kubectl exec -n ${_NAMESPACE} ${_POD_NAME} -- bash -c "
          mkdir -p /usr/share/nginx/html &&
          tar -xzf /tmp/latest_html.tar.gz -C /usr/share/nginx/html &&
          rm /tmp/latest_html.tar.gz
        "

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'cleanup'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Cleaning up temporary files..."
        rm -f /workspace/latest_html.tar.gz

substitutions:
  _GCE_VM: 'jumpserver'
  _PROJECT_ID: 'feisty-return-438307-f5'
  _BUCKET: 'demo-bucket-sql-dump'
  _REGION: 'us-central1'
  _ZONE: 'us-central1-c'
  _CLUSTER: 'demo-cluster-1'
  _POD_NAME: 'nginx-bf5d5cf98-ptvlj'
  _NAMESPACE: 'free'


options:
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'  # 20 minutes (adjust as needed)
